driver := ComObject("Selenium.ChromeDriver")
driver.Get("https://ahkv2.pnal.dev/playground/login")
driver.FindElementById("username").SendKeys("user")
driver.SendKeys(driver.Keys.Tab)
driver.SendKeys("1234")
driver.FindElementByXPath("/html/body/main/div/form/input").Click()
driver.Get("https://ahkv2.pnal.dev/playground/mypage")
originalText := driver.PageSource()
RegExMatch(originalText, "접속한 ID: (.*?)<br>", &output)
MsgBox(output[1])